[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
braille-ascii-art = { git = "https://github.com/Princic-1837592/image-to-braille", rev = "4dd0ef4fd000b6aaccdc90fd2dc831c20e043823" }
wasm-bindgen = "0.2.80"
