[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
braille-ascii-art = { git = "https://github.com/Princic-1837592/image-to-braille", rev = "39d0cf07f578b4973104debbb3cf944a7726f066" }
wasm-bindgen = "0.2.80"
